/**
 * Permanent contact-sheet harness for the /hoca-bul illustration family.
 *
 * One run shoots the whole visual matrix — every step in its default and
 * representative answered states, desktop light, desktop dark and the 390px
 * mobile band — into `screenshots/hoca-bul-illustrations/` (gitignored).
 *
 *   npx tsx scripts/hoca-bul-illustration-shots.ts
 *
 * The harness is self-contained: it writes a short-lived route shim that
 * mounts the permanent board (scripts/hoca-bul-illustration-board.tsx),
 * boots its own dev server on a dedicated port, captures, and then removes
 * the shim and stops the server. No review route remains in the app.
 *
 * Beyond the captures it asserts, and fails loudly on:
 *   - console errors during the run
 *   - horizontal overflow
 *   - bands not using their full 390px width
 *   - unsettled motion (any inline opacity short of 1 after the settle window)
 *   - artwork clipped against its viewBox
 *   - the intentional transforms (e.g. the pencil's lean) going missing
 */
import { chromium, type Page } from "playwright";
import { spawn } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const PORT = Number(process.env.HOCA_BUL_SHOTS_PORT ?? 3141);
const BASE_URL = `http://localhost:${PORT}`;
const ROUTE_DIR = path.join(ROOT, "src", "app", "illustration-review");
const STALE_TYPES = path.join(ROOT, ".next", "types", "app", "illustration-review");
const OUT_DIR = path.join(ROOT, "screenshots", "hoca-bul-illustrations");

/** Longer than the assembly contract's 1.1s ceiling, so every motion is done. */
const SETTLE_MS = 1600;

const SHIM = `/**
 * Generated by scripts/hoca-bul-illustration-shots.ts for one capture run and
 * deleted by the same run. Do not keep or hand-edit this shim.
 */
import { IllustrationReviewBoard } from "../../../scripts/hoca-bul-illustration-board";

export default function IllustrationReviewPage({
  searchParams,
}: {
  searchParams: { theme?: string };
}) {
  return <IllustrationReviewBoard dark={searchParams.theme === "dark"} />;
}
`;

function startDevServer() {
  // detached so the whole process group (npm wrapper + next) can be signalled.
  const child = spawn("npx", ["next", "dev", "-p", String(PORT)], {
    cwd: ROOT,
    detached: true,
    stdio: "ignore",
  });
  return {
    async waitReady(): Promise<void> {
      const deadline = Date.now() + 120_000;
      for (;;) {
        try {
          const response = await fetch(`${BASE_URL}/illustration-review`);
          if (response.ok) return;
        } catch {
          // not up yet
        }
        if (Date.now() > deadline) throw new Error("dev server did not come up");
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    },
    stop(): void {
      try {
        if (child.pid) process.kill(-child.pid, "SIGTERM");
      } catch {
        // already gone
      }
    },
  };
}

async function checkPage(page: Page, label: string): Promise<string[]> {
  const failures: string[] = [];

  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth > window.innerWidth
  );
  if (overflow) failures.push(`${label}: horizontal overflow`);

  const checks = await page.evaluate(() => {
    const problems: string[] = [];

    // Bands must use the full width their container gives them; on a wide
    // page the container is the product's 390px band.
    for (const band of Array.from(document.querySelectorAll("[data-band]"))) {
      const svg = band.querySelector("svg");
      const bandWidth = band.getBoundingClientRect().width;
      const width = svg?.getBoundingClientRect().width ?? 0;
      if (Math.abs(width - bandWidth) > 1) {
        problems.push(
          `band ${band.getAttribute("data-band")} leaves ${bandWidth - width}px unused`
        );
      }
      if (window.innerWidth >= 768 && Math.abs(bandWidth - 390) > 1) {
        problems.push(
          `band ${band.getAttribute("data-band")} is ${bandWidth}px, not the product's 390px`
        );
      }
    }

    for (const svg of Array.from(document.querySelectorAll("svg[data-step]"))) {
      // Motion must be settled: nothing left semi-transparent.
      for (const el of Array.from(svg.querySelectorAll("*"))) {
        const opacity = (el as HTMLElement).style?.opacity;
        if (opacity && Number(opacity) < 1) {
          problems.push(`${svg.getAttribute("data-step")}: unsettled motion`);
          break;
        }
      }

      // Artwork must not be clipped by its own viewBox.
      const viewBox = (svg.getAttribute("viewBox") ?? "").split(" ").map(Number);
      const bbox = (svg as SVGSVGElement).getBBox();
      const tolerance = 3; // stroke width
      if (
        bbox.x < viewBox[0] - tolerance ||
        bbox.y < viewBox[1] - tolerance ||
        bbox.x + bbox.width > viewBox[0] + viewBox[2] + tolerance ||
        bbox.y + bbox.height > viewBox[1] + viewBox[3] + tolerance
      ) {
        problems.push(`${svg.getAttribute("data-step")}: clipped artwork`);
      }
    }

    // Intentional transforms (the pencil's lean) must survive.
    const transformed = document.querySelectorAll(
      'svg[data-step="hoca_yaklasimi"] g[transform]'
    );
    if (transformed.length === 0) problems.push("pencil transform missing");

    return problems;
  });

  failures.push(...checks.map((problem) => `${label}: ${problem}`));
  return failures;
}

async function capture(
  page: Page,
  theme: "light" | "dark",
  viewport: { width: number; height: number },
  file: string
): Promise<string[]> {
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });

  await page.goto(`${BASE_URL}/illustration-review?theme=${theme}`, {
    waitUntil: "networkidle",
    timeout: 60_000,
  });
  await page.waitForTimeout(SETTLE_MS);

  const failures = await checkPage(page, `${theme} @ ${viewport.width}px`);
  if (consoleErrors.length > 0) {
    failures.push(`${theme}: console errors: ${consoleErrors.join(" | ")}`);
  }

  await page.screenshot({ path: path.join(OUT_DIR, file), fullPage: true });
  console.log(`saved ${file}`);
  return failures;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(ROUTE_DIR, { recursive: true });
  await writeFile(path.join(ROUTE_DIR, "page.tsx"), SHIM);

  const server = startDevServer();
  const failures: string[] = [];
  const browser = await chromium.launch();

  try {
    await server.waitReady();

    for (const theme of ["light", "dark"] as const) {
      const context = await browser.newContext({
        viewport: { width: 1280, height: 900 },
      });
      const page = await context.newPage();
      failures.push(
        ...(await capture(
          page,
          theme,
          { width: 1280, height: 900 },
          `illustrations-desktop-${theme}.png`
        ))
      );
      await context.close();
    }

    const context = await browser.newContext({
      viewport: { width: 390, height: 844 },
    });
    const page = await context.newPage();
    failures.push(
      ...(await capture(
        page,
        "light",
        { width: 390, height: 844 },
        "illustrations-mobile-band-light.png"
      ))
    );
    await context.close();
  } finally {
    await browser.close();
    server.stop();
    await rm(ROUTE_DIR, { recursive: true, force: true });
    await rm(STALE_TYPES, { recursive: true, force: true });
  }

  if (failures.length > 0) {
    for (const failure of failures) console.log(`FAIL: ${failure}`);
    process.exitCode = 1;
  } else {
    console.log("PASS: no overflow, no clipping, bands full width, motion settled, no console errors");
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
